#!/bin/sh

N=5 # number of times a test is repeated (to get an average)

# TIP: You can edit the list of input sizes below
for size in 10000 25000 50000 75000 100000 250000 500000 1000000
do
	# TIP: You can edit the list of input types below
	#      For example, you could remove 'random' if you don't want to
	#      time with random input
	for order in random sorted reversed
	do
		echo === Testing for $order input, size $size ===
		for i in $(seq $N)
		do
			case $order in
				random)   flag="R" ;;
				sorted)   flag="A" ;;
				reversed) flag="D" ;;
			esac
			# Use timeout to limit execution time to 60 seconds
			if ! { ./gen $size $flag | timeout 120s /usr/bin/time -f "%U" ./sortB > /dev/null ; } then
    			echo "NULL"
			fi
			#                          TIP: replace this ^ with ./sortA or ./sortB
		done
		echo ""
	done
done

